[build-dependencies]
bindgen = '0.64.0'
anyhow='1.0.69'
fs_extra='1.3.0'

[dependencies]
pest = '2.1.3'
pest_consume = '1.1.1'
pest_derive = '2.1.0'

[package]
edition = '2021'
name = 'necrs'
version = '0.1.0'
